# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db1903dd011f95b6402dc89955de106a7a352f89b8c79dd167d306a9a4b38f23fe77eac0e3b8ff5b1b55ac0ed33128673a321a066558815ab050ded17a717ff8

test:
  secret_key_base: 571ab73602bc01c00b187810665401e4361374796b1b7e5a77e0b84794f41b8de9c68282d88fec53c4c803044ddfc7fa1e00a162cfb9d2cedefaa6571393d921

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
